dynamodb:
  image: ryanratcliff/dynamodb
  restart: always
  volumes:
    - /var/dynamodb_data:/var/dynamodb_data
  ports:
    - "8000"

redis:
  image: redis
  restart: always
  ports:
    - "6379"

url-shortener:
  image: philmod/url-shortener
  ports:
    - "80:3070"
  links:
    - dynamodb
    - redis
  environment:
    NODE_ENV: staging
